name: Run Benchmarks

on:
  push:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # Checkout the benchmark results repository first
      - name: Checkout benchmark repository
        uses: actions/checkout@v3
        with:
          repository: folk-canvas/folk-canvas-benchmarks
          path: folk-canvas-benchmarks
          token: ${{ secrets.BENCHMARK_REPO_TOKEN }}

      # Run benchmarks with path to existing results
      - name: Run benchmarks
        run: BENCHMARK_HISTORY_PATH=folk-canvas-benchmarks/mitata_benchmarks.json node _scripts_/benchmark.js

      # Commit and push updates
      - name: Update benchmark results
        run: |
          cd folk-canvas-benchmarks
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mitata_benchmarks.json
          git commit -m "Update benchmark results for ${{ github.sha }}"
          git push
